name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish HealthChecks.Extensions.AzureSearch
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: HealthChecks.Extensions.AzureSearch/HealthChecks.Extensions.AzureSearch.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HealthChecks.Extensions.AzureWebjob
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: HealthChecks.Extensions.AzureWebjob/HealthChecks.Extensions.AzureWebjob.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}